name: "Publish Node.js MCP"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-mcps-changes.yaml
    permissions:
      pull-requests: read
      contents: read

  publish-node-mcp:
    name: Publish Node MCP
    runs-on: macos-26
    needs: detect-changes
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
    permissions:
      contents: read
      id-token: write
    if: needs.detect-changes.outputs.has_node_changes == 'true'
      && !contains(github.event.pull_request.title, '[skip ci]')
      && github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        mcp: ${{ fromJson(needs.detect-changes.outputs.node_mcps) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        with:
          token_format: access_token
          workload_identity_provider: projects/77571513357/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-pool-provider
          service_account: gh-action-eney@macpaw-devops.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Setup CLI
        uses: ./.github/actions/setup-cli

      - name: Publish MCP
        run: eney-skills-cli publish --mode production
        working-directory: extensions/${{ matrix.mcp }}
