name: "Upload Extension archive"

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: Detect changes in extensions
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      extensions: ${{ steps.print-changes.outputs.extensions }}
      has_changes: ${{ steps.print-changes.outputs.has_changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check for extension changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          list-files: json
          filters: |
            extensions:
              - 'extensions/**'

      - name: Print changed extensions
        id: print-changes
        uses: actions/github-script@v8
        with:
          script: |
            const filePaths = JSON.parse('${{ steps.filter.outputs.extensions_files }}');
            const extensions = filePaths
              .filter(path => path.startsWith('extensions/'))
              .map(path => {
                const segments = path.split('/');
                if (segments.length < 2) {
                  return null;
                }

                return segments[1];
              })
              .filter((ext, index, self) => self.indexOf(ext) === index)
              .filter((ext) => ext !== null);

            console.log(JSON.stringify(extensions, null, 2));
            core.setOutput('extensions', extensions);
            core.setOutput('has_changes', extensions.length > 0);

  uploadExtensionArchive:
    name: Upload extension archive
    runs-on:
      group: gcp-k8s
    needs: changes
    permissions:
      contents: read
      id-token: write
    if: needs.changes.outputs.has_changes == 'true'
    strategy:
      matrix:
        extension: ${{ fromJson(needs.changes.outputs.extensions) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        with:
          token_format: access_token
          workload_identity_provider: projects/77571513357/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-pool-provider
          service_account: gh-action-eney@macpaw-devops.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies for CLI
        run: |
          npm i --prefix cli

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.ORG_GHA_TOKEN_NPMJS_PACKAGES_RO }}"

      - name: Bundle extension
        run: |
          node cli/main.ts bundle --cwd extensions/${{ matrix.extension }} -o dist

      - name: Publish extension
        run: |
          node cli/main.ts publish --cwd extensions/${{ matrix.extension }}
        env:
          BACKEND_URL: https://core.eney.appflix.io
          ADMIN_ACCESS_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}

      - name: Get extension version
        id: get-extension-version
        run: |
          VERSION=$(cat extensions/${{ matrix.extension }}/manifest.json | jq -r '.version')
          echo "Extension version: $VERSION"
          echo "EXTENSION_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Get archive name
        id: get-archive-name
        run: |
          ARCHIVE_NAME=${{ matrix.extension }}@v${{ steps.get-extension-version.outputs.EXTENSION_VERSION }}.zip
          echo "Archive name: $ARCHIVE_NAME"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: Create extension archive
        run: |
          cd dist
          zip -r ${{ steps.get-archive-name.outputs.ARCHIVE_NAME }} ${{ matrix.extension }}

      - name: Upload Extension Archive
        uses: google-github-actions/upload-cloud-storage@6397bd7208e18d13ba2619ee21b9873edc94427a # v3
        with:
          path: dist/${{ steps.get-archive-name.outputs.ARCHIVE_NAME }}
          destination: "eney-assets/extensions"
          predefinedAcl: "publicRead"
          process_gcloudignore: false
