name: "Upload Extension archive"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-extension-changes.yaml
    permissions:
      pull-requests: read
      contents: read

  uploadExtensionArchive:
    name: Upload extension archive
    runs-on:
      group: gcp-k8s
    needs: detect-changes
    permissions:
      contents: read
      id-token: write
    if: needs.detect-changes.outputs.has_changes == 'true'
    env:
      IS_DRY_RUN: ${{ github.event_name == 'pull_request' }}
      BACKEND_URL: https://core.eney.appflix.io
      ADMIN_AUTH_TOKEN: ${{ secrets.ADMIN_AUTH_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        extension: ${{ fromJson(needs.detect-changes.outputs.extensions) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        if: env.IS_DRY_RUN != 'true'
        with:
          token_format: access_token
          workload_identity_provider: projects/77571513357/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-pool-provider
          service_account: gh-action-eney@macpaw-devops.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Setup CLI
        uses: ./.github/actions/setup-cli
        with:
          npm_token: ${{ secrets.ORG_GHA_TOKEN_NPMJS_PACKAGES_RO }}

      - name: Check extension version
        run: node cli/main.ts check-version --cwd extensions/${{ matrix.extension }}

      - name: Publish extension
        run: node cli/main.ts publish --cwd extensions/${{ matrix.extension }} --mode staging

      - name: Publish extension
        run: |
          DRY_RUN_ARG=""

          if [ "${{ env.IS_DRY_RUN }}" = "true" ]; then
            DRY_RUN_ARG="--dry-run"
          fi

          node cli/main.ts publish \
            --cwd extensions/${{ matrix.extension }} \
            --mode staging \
            $DRY_RUN_ARG
